version: '3.8'

services:
  stock-db:
    image: postgres:13
    container_name: stock-db
    environment:
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_password
      POSTGRES_DB: stock_db
    ports:
      - "5432:5432"
    volumes:
      - stock-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  history-db:
    image: postgres:13
    container_name: history-db
    environment:
      POSTGRES_USER: history_user
      POSTGRES_PASSWORD: history_password
      POSTGRES_DB: history_db
    ports:
      - "5433:5432"
    volumes:
      - history-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  stock-service:
    build:
      context: ./stock-service
    container_name: stock-service
    env_file:
      - ./stock-service/.env
    ports:
      - "3001:3001"
    depends_on:
      - stock-db
    networks:
      - app-network
    restart: "on-failure"

  history-service:
    build:
      context: ./history-service
    container_name: history-service
    env_file:
      - ./history-service/.env
    ports:
      - "3000:3000"
    depends_on:
      - history-db
    networks:
      - app-network
    restart: "on-failure"

  stock-service-migrations:
    build:
      context: ./stock-service
    container_name: stock-service-migrations
    command: ["npx", "prisma", "migrate", "deploy"]
    depends_on:
      - stock-db
    networks:
      - app-network
    restart: "on-failure"

  stock-service-seed:
    build:
      context: ./stock-service
    container_name: stock-service-seed
    command: ["npx", "ts-node", "prisma/seed.ts"]
    depends_on:
      - stock-service-migrations
    networks:
      - app-network
    restart: "on-failure"

  history-service-migrations:
    build:
      context: ./history-service
    container_name: history-service-migrations
    command: ["npx", "prisma", "migrate", "deploy"]
    depends_on:
      - history-db
    networks:
      - app-network
    restart: "on-failure"

volumes:
  stock-data:
  history-data:

networks:
  app-network:
    driver: bridge


